### ISSUE TITLE
插件小面板窗口不生效

### ISSUE THREAD

**Issue by zyy515** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#1]
QQ版本：9.9.2-16183
![屏幕截图 2024-01-26 205208](https://github.com/hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic/assets/127068653/b8ef6b76-47e2-4e81-880e-c55ae410ba87)

**Comment by hacker-frok** [comment]
更新下最新版本，不过，你这版本太低了吧，而且LiteLoaderQQNT是1.0.0及以上么

**Comment by zyy515** [comment]
LiteLoaderQQNT是1.0.3的，之前0.X版本的时候更新QQ就不生效了，找了一些激活方式没成功，最后发现有个方式支持最高版本到QQ9.9.2就把QQ回退到这个版本了。不过我试了一下最新版的插件仍然是无效的，所以QQ应该更新到哪个版本比较好嘞？我不是很喜欢更新QQ，因为QQ总是越更里面加一些用不上的东西。

**Comment by hacker-frok** [comment]
> LiteLoaderQQNT是1.0.3的，之前0.X版本的时候更新QQ就不生效了，找了一些激活方式没成功，最后发现有个方式支持最高版本到QQ9.9.2就把QQ回退到这个版本了。不过我试了一下最新版的插件仍然是无效的，所以QQ应该更新到哪个版本比较好嘞？我不是很喜欢更新QQ，因为QQ总是越更里面加一些用不上的东西。

其它主题影响了吧，你先去掉其它主题看看，最新版是窗口变小，变到小面板就会自动变成怀旧模式

**Comment by zyy515** [comment]
我先是把QQ更新到最新版，但是还是不生效，然后把主题关闭后生效了。后面把主题再开启仍然有效果。也不清楚是版本的问题还是应该先关主题再开插件后重新开主题。可惜我没在旧版本试过，不过现在的确是可以用了

**Comment by hacker-frok** [comment]
> 我先是把QQ更新到最新版，但是还是不生效，然后把主题关闭后生效了。后面把主题再开启仍然有效果。也不清楚是版本的问题还是应该先关主题再开插件后重新开主题。可惜我没在旧版本试过，不过现在的确是可以用了

你用的哪个主题，发一下，我看看是哪个样式被覆盖了

**Comment by zyy515** [comment]
https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme
