### ISSUE TITLE
25765版本修改了QQ头像的样式，导致头像下移

### ISSUE THREAD

**Issue by Whuihuan** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#10]
这个版本在头像顶上加了个QQ9字样，然后给头像做了20px的向下偏移，导致开启怀旧模式后，怀旧模式的头像也跟着下移20px

**Comment by hacker-frok** [comment]
> 这个版本在头像顶上加了个QQ9字样，然后给头像做了20px的向下偏移，导致开启怀旧模式后，怀旧模式的头像也跟着下移20px

上个图片看看？

**Comment by Whuihuan** [comment]
变更后：
![QQ_1721307120106](https://github.com/user-attachments/assets/2887064f-8cdc-420d-a873-8e3d96c7ef88)
![QQ_1721307131088](https://github.com/user-attachments/assets/f605edd0-daf3-41cb-993c-5bdb22e1b72d)
变更前：
![QQ_1721307223664](https://github.com/user-attachments/assets/f4d13b2a-fdf7-4a4b-942b-4b023eee9d34)
![QQ_1721307249524](https://github.com/user-attachments/assets/be556e9c-907b-4e40-8bdd-7205c24629ba)

**Comment by hacker-frok** [comment]
已修复
