### ISSUE TITLE
怀旧模式在新版QQ9.9.15-26702失效了

### ISSUE THREAD

**Issue by as88866920** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#12]
怀旧模式在新版QQ9.9.15-26702失效了
![240f91c8-8add-414e-a3f0-85bec0ea11aa](https://github.com/user-attachments/assets/73ebde75-9f4e-4cdc-b140-8abeb3076c44)
连昵称和列表名字都没有了

**Comment by as88866920** [comment]
作者不在了吗？

**Comment by as88866920** [comment]
没人更新了吗？

**Comment by as88866920** [comment]
怀旧模式在新版QQ9.9.15-26702失效了

**Comment by as88866920** [comment]
怀旧模式在新版QQ9.9.15-26702失效了

**Comment by Hisssy** [comment]
#17 可以测试下这个 PR

**Comment by as88866920** [comment]
> #17 可以测试下这个 PR

![QQ20241021-011145](https://github.com/user-attachments/assets/c60e79c6-e21e-4cdd-86b2-63f68d346d56)
变这样了

**Comment by Hisssy** [comment]
> > #17 可以测试下这个 PR
> > 现在已经9.9.15-28498
> > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > 变这样了

这里的变量竟然会被重新定义，我改了一下，可以再试试。

**Comment by hacker-frok** [comment]
> > > #17 可以测试下这个 PR
> > > 现在已经9.9.15-28498
> > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > 变这样了
> 
> 这里的变量竟然会被重新定义，我改了一下，可以再试试。

不错的pr，顺便把其它bug也修了，我抽空合并一下...

**Comment by as88866920** [comment]
> > > #17 可以测试下这个 PR
> > > 现在已经9.9.15-28498
> > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > 变这样了
> 
> 这里的变量竟然会被重新定义，我改了一下，可以再试试。

还是一样没用

**Comment by as88866920** [comment]
> > > > #17 可以测试下这个 PR
> > > > 现在已经9.9.15-28498
> > > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > > 变这样了
> > 
> > 
> > 这里的变量竟然会被重新定义，我改了一下，可以再试试。
> 
> 不错的pr，顺便把其它bug也修了，我抽空合并一下...

快来修复了

**Comment by TSKG** [comment]
快来修复，确实是坏的

**Comment by TSKG** [comment]
> > > > > #17 可以测试下这个 PR
> > > > > 现在已经9.9.15-28498
> > > > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > > > 变这样了
> > > 
> > > 
> > > 这里的变量竟然会被重新定义，我改了一下，可以再试试。
> > 
> > 
> > 不错的pr，顺便把其它bug也修了，我抽空合并一下...
> 
> 快来修复了

试过了，修复了

**Comment by as88866920** [comment]
> > > > > > #17 可以测试下这个 PR
> > > > > > 现在已经9.9.15-28498
> > > > > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > > > > 变这样了
> > > > 
> > > > 
> > > > 这里的变量竟然会被重新定义，我改了一下，可以再试试。
> > > 
> > > 
> > > 不错的pr，顺便把其它bug也修了，我抽空合并一下...
> > 
> > 
> > 快来修复了
> 
> 试过了，修复了

哪里修复了？

**Comment by as88866920** [comment]
> > > > > > #17 可以测试下这个 PR
> > > > > > 现在已经9.9.15-28498
> > > > > > ![QQ20241021-011145](https://private-user-images.githubusercontent.com/139908494/378210254-c60e79c6-e21e-4cdd-86b2-63f68d346d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODkzNzgsIm5iZiI6MTcyOTQ4OTA3OCwicGF0aCI6Ii8xMzk5MDg0OTQvMzc4MjEwMjU0LWM2MGU3OWM2LWUyMWUtNGNkZC04NmIyLTYzZjY4ZDM0NmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNTM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQxZDdjMmU5MTVjNWQzZjM2YzNlNTY4YzRmOTQwY2E0Mjg3YzlkNmIyZmM4MGJiNjM3NzNhMzY1MDIxYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ztkZXZBc1ThKvTkY-Tt1jDHCdrL4YXip3xDSxMyVKFY)
> > > > > > 变这样了
> > > > 
> > > > 
> > > > 这里的变量竟然会被重新定义，我改了一下，可以再试试。
> > > 
> > > 
> > > 不错的pr，顺便把其它bug也修了，我抽空合并一下...
> > 
> > 
> > 快来修复了
> 
> 试过了，修复了

修复个鬼
没有修复
![Uploading QQ20241021-234714.png…]()

**Comment by Hisssy** [comment]
@as88866920 你的截图没上传完全，看不到报错。我这边测试是正常的。
![pic](https://github.com/user-attachments/assets/f3c68d76-64ad-4377-869d-39a8f3d4fde1)

**Comment by as88866920** [comment]
> @as88866920 你的截图没上传完全，看不到报错。我这边测试是正常的。 ![pic](https://private-user-images.githubusercontent.com/20365878/378504567-f3c68d76-64ad-4377-869d-39a8f3d4fde1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjcwMzAsIm5iZiI6MTcyOTUyNjczMCwicGF0aCI6Ii8yMDM2NTg3OC8zNzg1MDQ1NjctZjNjNjhkNzYtNjRhZC00Mzc3LTg2OWQtMzlhOGYzZDRmZGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZTcyNWY0OTViMGEwYjdhOTFhMzlhMzMwYThmYmE0ODcxODMyNTgwZWRjMmIxYzBiMGQ1M2Q3MjdlMTVjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3_fNCUE273gegv9pGxTcHBizGrpBP26olC2UxjJDK8)

你直接打包好，发个包我试试

**Comment by Hisssy** [comment]
哥们，你直接下载 master 呗。。或者把 main.js 这个文件整个替换一下。

> > @as88866920 你的截图没上传完全，看不到报错。我这边测试是正常的。 ![pic](https://private-user-images.githubusercontent.com/20365878/378504567-f3c68d76-64ad-4377-869d-39a8f3d4fde1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjcwMzAsIm5iZiI6MTcyOTUyNjczMCwicGF0aCI6Ii8yMDM2NTg3OC8zNzg1MDQ1NjctZjNjNjhkNzYtNjRhZC00Mzc3LTg2OWQtMzlhOGYzZDRmZGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZTcyNWY0OTViMGEwYjdhOTFhMzlhMzMwYThmYmE0ODcxODMyNTgwZWRjMmIxYzBiMGQ1M2Q3MjdlMTVjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3_fNCUE273gegv9pGxTcHBizGrpBP26olC2UxjJDK8)
> 
> 你直接打包好，发个包我试试

**Comment by as88866920** [comment]
> maste

可以的话直接加QQ得了
 master哪里下？

**Comment by Hisssy** [comment]
[LiteLoaderQQNT-Plugin-Nostalgic-main.zip](https://github.com/user-attachments/files/17464097/LiteLoaderQQNT-Plugin-Nostalgic-main.zip)

**Comment by Hisssy** [comment]
[LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip](https://github.com/user-attachments/files/17464111/LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip)

**Comment by as88866920** [comment]
> [LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip](https://github.com/user-attachments/files/17464111/LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip)

OK，好了谢谢

**Comment by as88866920** [comment]
> [LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip](https://github.com/user-attachments/files/17464111/LiteLoaderQQNT-Plugin-Nostalgic-fix-1.zip)

还有个问题就是，怀旧模式下。邮箱图标在右下角。有邮件时点击不了
![QQ20241022-002634](https://github.com/user-attachments/assets/016a05f3-4f0e-428d-8956-e8336ff914a1)

**Comment by hacker-frok** [comment]
大佬们，最新版本已适配
