### ISSUE TITLE
期待可以将功能栏内的 消息/联系人/空间 单独列出来放到上面或者下面

### ISSUE THREAD

**Issue by HMwancheng** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#2]
![image](https://github.com/hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic/assets/91036325/1fe5b963-8006-42d2-9459-337fff6936c4)
期待可以将功能栏内的 消息/联系人/空间 单独列出来放到上面或者下面，这样就不用切换联系人/消息的时候多次点击了，且更像旧版AWA

**Comment by HMwancheng** [comment]
另可以的话希望能增加一个自动控制高度的功能，如上图，仅有4个图标的情况下仍然占用了全图标高度

感谢作者大大！

**Comment by hacker-frok** [comment]
新版本已实现

**Comment by HMwancheng** [comment]
☆*: .｡. o(≧▽≦)o .｡.:*☆
