### ISSUE TITLE
[Bug] 似乎偶爾會出現啟動後未套用小面板窗口模式

### ISSUE THREAD

**Issue by TW527E** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#6]
### Check List: 
- [x] 使用搜尋功能，確定 Issues 中沒有相似問題
- [ ] 確定該問題是穩定可復現的
- [ ] 確定不是其他插件造成的

### 問題描述: 
似乎在啟動後有概率遇到沒有套用小面板窗口模式的情況，不確定具體的原因(例如是其他插件造成的，又或是該插件自身的問題)，因為尚未發現一個規律可以復現該問題。

### 版本: 
- 系統 : Windows 11 Pro 23H2 22631.3374
- QQNT : 9.9.8-22401
- LiteLoaderQQNT : 1.0.3
- Chromiunm : 120.0.6099.56
- Eletron : 28.0.0
- Node.js : 18.18.2
- 本插件版本 : 1.1.7

### 已安裝插件: 
1. Audio Sender : 1.0.1
2. DeepL : 1.1.1
3. 使用自定义浏览器打开链接并跳过拦截页 : 0.1.3
4. 插件商店 : 2.0.1
5. 轻量工具箱 : 2.22.3
6. 本地查看图片和视频 : 0.1.14
7. More Materials : 1.0.0
8. QQ怀旧模式 : 1.1.7 (本插件)
9. MSpring Theme : 1.3.0
10. Transitio : 1.2.0

### 本插件設定: 
- 启用Header面板染色 : ✖️
- Header面板背景颜色 : #686cdf #e3b5d9
- Header面板文字颜色 : #ffffff
- Header面板文字颜色透明度 : 79
- 强制小面板窗口模式 : ✔️
- 隐藏右上角的折叠按钮 : ✔️
- 旧版列表样式 : ✔️
`{"useOldTheme":false,"themeColor":"#686cdf","themeColor2":"#e3b5d9","themeColor3":"#ffffff","backgroundOpacity":"79","isDebug":false,"useOldThemeWin":true,"hideSwitchBtn":true,"useOldThemeMegList":true}`

**Comment by QingFeng-awa** [comment]
早在4月26日这个issue就被标记为bug了，现在马上就是6月1日了,有什么进展么?

**Comment by TW527E** [comment]
> 早在4月26日这个issue就被标记为bug了，现在马上就是6月1日了,有什么进展么?

什麼都沒有😶‍🌫️

**Comment by QingFeng-awa** [comment]
hacker加了个bug Label就没有然后了……
真是够了………………

**Comment by hacker-frok** [comment]
> 早在4月26日这个issue就被标记为bug了，现在马上就是6月1日了,有什么进展么?

嗯，最近刚过完61，后面抽空看看😆

**Comment by QingFeng-awa** [comment]
这个插件是不是可以归档了

**Comment by QingFeng-awa** [comment]
7月了怎么还不更新……

**Comment by hacker-frok** [comment]
> 7月了怎么还不更新……

在上班赚奶粉...

**Comment by hacker-frok** [comment]
最新版本已修复
