### ISSUE TITLE
Bug: 启动时有概率未正常加载

### ISSUE THREAD

**Issue by QingFeng-awa** [hacker-frok/LiteLoaderQQNT-Plugin-Nostalgic#9]
### QQNT版本
9.9.9-23424
### LiteLoaderQQNT版本
1.1.1
### 运行环境
Windows 11 23H2
### 重现步骤
_**在我的电脑上,这是偶然发生的问题,因此我不知道如何100%复现问题。**_
### 期望的结果
正常加载。
### 实际的结果
没有加载旧版QQ布局,但正常加载了靠顶部吸附的动画。
### 日志信息
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-23424
[preload] hotupdate current version: 9.9.9-23424
[preload] install app version: 9.9.9-23424

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\wrapper.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: QQ纯享模式
[LiteLoader] Found plugin: QQCleaner
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: 演示模式
[LiteLoader] Found plugin: 使用自定义浏览器打开链接并跳过拦截页
[LiteLoader] Found plugin: Euphony
[LiteLoader] Found plugin: Fake Message
[LiteLoader] Found plugin: 繁化姬 (Incompatible)
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: 本地查看图片和视频
[LiteLoader] Found plugin: More Materials
[LiteLoader] Found plugin: MSpring Theme (Disabled)
[LiteLoader] Found plugin: QQ怀旧模式
[LiteLoader] Found plugin: pURLfy
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found plugin: Scriptio
[LiteLoader] Found plugin: Transitio
[LiteLoader] Found 18 plugins, start loading plugins.
[preload] register done. launcher.node
[preload] register done. major.node
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
[LLAPI] Page finished loading
返回配置文件 {}
[LLAPI] Page finished loading
返回配置文件 {}
使用默认配置
更新配置文件 {
  debug: {
    console: false,
    mainConsole: false,
    autoCompileScss: false,
    showWeb: false,
    showChannedCommunication: false
  },
  compatibleLLAPI: false,
  keywordReminder: { enabled: false, keyList: [] },
  wordSearch: {
    enabled: true,
    searchUrl: 'https://www.bing.com/search?q=%search%'
  },
  imageSearch: {
    enabled: false,
    searchUrl: 'https://saucenao.com/search.php?url=%search%'
  },
  localEmoticons: {
    enabled: true,
    quickEmoticons: false,
    quickEmoticonsAutoInputOnlyOne: false,
    quickEmoticonsActiveKey: '/',
    sendBigImage: false,
    majorization: true,
    commonlyEmoticons: false,
    copyFileTolocalEmoticons: true,
    toLeftSlot: true,
    hoverShowCommonlyEmoticons: false,
    commonlyNum: 28,
    rowsSize: 6,
    localPath: 'C:\\Program Files\\LiteLoaderQQNT\\LocalExpression'
  },
  sidebar: {
    top: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    bottom: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  imageViewer: { quickClose: false, touchMove: false },
  message: {
    previreUrl: { enabled: true, dontLoadPic: false },
    goBackMainList: true,
    HighlightReplies: true,
    disabledSticker: true,
    disabledHotGIF: true,
    disabledBadge: false,
    disabledSlideMultipleSelection: false,
    convertMiniPrgmArk: true,
    showMsgTime: true,
    showMsgTimeFullDate: true,
    showMsgTimeToSenderName: true,
    replaceBtn: true,
    doubleClickReplace: true,
    removeReplyAt: true,
    mergeMessage: true,
    mergeMessageKeepTime: true,
    selfMsgToLeft: false,
    onlyAvatar: false,
    removeBubbleLimit: true,
    removeVipName: false,
    imageAutoWidth: true,
    currentLocation: false,
    overrideFont: { family: '', style: '', fullName: '', postscriptName: '' },
    preventNSFW: { enabled: false, includesAnimationEmoticons: false, list: [] },
    avatarSticky: { enabled: true, toBottom: false }
  },
  messageToImage: { enabled: false, highResolution: false, path: '' },
  preventMessageRecall: {
    enabled: true,
    localStorage: true,
    customColor: true,
    preventSelfMsg: true,
    blockAllRetractions: true,
    textColor: { light: '#ff6666', dark: '#c70000' }
  },
  tail: { enabled: false, tips: false, list: [ [Object] ] },
  textAreaFuncList: [
    { name: '表情', id: 'id-func-bar-expression', disabled: false },
    { name: '截图', id: 'id-func-bar-screenshot', disabled: true },
    { name: '文件', id: 'id-func-bar-folder', disabled: false },
    { name: '图片', id: 'id-func-bar-image', disabled: false },
    { name: '红包', id: 'id-func-bar-lucky_money', disabled: true },
    { name: '语音消息', id: 'id-func-bar-microphone_on', disabled: true },
    { name: '机器人指令', id: 'id-func-bar-channel_robot', disabled: true },
    { name: '聊天记录', id: 'id-func-bar-MessageRecord', disabled: false },
    { name: '翻译', id: 'deepl-bar-icon', disabled: false },
    { name: '窗口抖动', id: 'id-func-bar-shake', disabled: false }
  ],
  chatAreaFuncList: [
    { name: '语音通话', id: 'id-func-bar-telephone', disabled: true },
    { name: '视频通话', id: 'id-func-bar-video_on', disabled: true },
    { name: '屏幕共享', id: 'id-func-bar-share_screen', disabled: true },
    {
      name: '群应用',
      id: 'id-func-bar-group_application',
      disabled: false
    },
    { name: '邀请加群', id: 'id-func-bar-group_building', disabled: false },
    { name: '工具栏项目', id: 'id-func-bar-more', disabled: false },
    { name: '发起群聊', id: 'id-func-bar-group_building', disabled: true },
    { name: '远程协助', id: 'id-func-bar-remote_control', disabled: true },
    { name: '屏蔽会话', id: 'id-func-bar-shield', disabled: false },
    { name: '添加好友', id: 'id-func-bar-add_friend', disabled: false },
    { name: '接收会话', id: 'id-func-bar-shield', disabled: false },
    { name: null, id: 'id-func-bar-more', disabled: true }
  ],
  preventEscape: false,
  advanceHookVue: true,
  setWindowIcon: true,
  autoRelanch: false,
  background: {
    overlaySiderBar: true,
    removeMask: false,
    redrawCard: true,
    backgroundVisible: true,
    blurFilter: true,
    opacity: 1,
    enabled: false,
    url: 'C:\\Users\\QingYu\\OneDrive\\图片\\Windows\\XtremeWave.png'
  },
  global: {
    UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    rkey: '&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64',
    PIC_BASE_URL: 'https://gchat.qpic.cn'
  },
  disableQtag: { level: false, title: false, all: false }
}
[2024/5/18 21:12:54][QQCleaner] Main window detected!
[2024/5/18 21:12:54][QQCleaner] QQCleaner has been initialized!
[2024/5/18 21:12:54][QQCleaner] Startup clean will be start in 5s...
[2024/5/18 21:12:54][QQCleaner] Clean clock registed, cleaning will be start every 14 hours.
Image-Local-View: NTQQ Image-Local-View for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
[!Renderer:Log:2] [DeepL] 已检测到 #ml-root .ml-list
[!Renderer:Log:2] [Media-Local-View] 检测到聊天区域，已在当前页面加载视频下载辅助
更新配置文件 {
  debug: {
    console: false,
    mainConsole: false,
    autoCompileScss: false,
    showWeb: false,
    showChannedCommunication: false
  },
  compatibleLLAPI: false,
  keywordReminder: { enabled: false, keyList: [] },
  wordSearch: {
    enabled: true,
    searchUrl: 'https://www.bing.com/search?q=%search%'
  },
  imageSearch: {
    enabled: false,
    searchUrl: 'https://saucenao.com/search.php?url=%search%'
  },
  localEmoticons: {
    enabled: true,
    quickEmoticons: false,
    quickEmoticonsAutoInputOnlyOne: false,
    quickEmoticonsActiveKey: '/',
    sendBigImage: false,
    majorization: true,
    commonlyEmoticons: false,
    copyFileTolocalEmoticons: true,
    toLeftSlot: true,
    hoverShowCommonlyEmoticons: false,
    commonlyNum: 28,
    rowsSize: 6,
    localPath: 'C:\\Program Files\\LiteLoaderQQNT\\LocalExpression'
  },
  sidebar: {
    top: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    bottom: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  imageViewer: { quickClose: false, touchMove: false },
  message: {
    previreUrl: { enabled: true, dontLoadPic: false },
    goBackMainList: true,
    HighlightReplies: true,
    disabledSticker: true,
    disabledHotGIF: true,
    disabledBadge: false,
    disabledSlideMultipleSelection: false,
    convertMiniPrgmArk: true,
    showMsgTime: true,
    showMsgTimeFullDate: true,
    showMsgTimeToSenderName: true,
    replaceBtn: true,
    doubleClickReplace: true,
    removeReplyAt: true,
    mergeMessage: true,
    mergeMessageKeepTime: true,
    selfMsgToLeft: false,
    onlyAvatar: false,
    removeBubbleLimit: true,
    removeVipName: false,
    imageAutoWidth: true,
    currentLocation: false,
    overrideFont: { family: '', style: '', fullName: '', postscriptName: '' },
    preventNSFW: { enabled: false, includesAnimationEmoticons: false, list: [] },
    avatarSticky: { enabled: true, toBottom: false }
  },
  messageToImage: { enabled: false, highResolution: false, path: '' },
  preventMessageRecall: {
    enabled: true,
    localStorage: true,
    customColor: true,
    preventSelfMsg: true,
    blockAllRetractions: true,
    textColor: { light: '#ff6666', dark: '#c70000' }
  },
  tail: { enabled: false, tips: false, list: [ [Object] ] },
  textAreaFuncList: [
    { name: '表情', id: 'id-func-bar-expression', disabled: false },
    { name: '截图', id: 'id-func-bar-screenshot', disabled: true },
    { name: '文件', id: 'id-func-bar-folder', disabled: false },
    { name: '图片', id: 'id-func-bar-image', disabled: false },
    { name: '红包', id: 'id-func-bar-lucky_money', disabled: true },
    { name: '语音消息', id: 'id-func-bar-microphone_on', disabled: true },
    { name: '机器人指令', id: 'id-func-bar-channel_robot', disabled: true },
    { name: '聊天记录', id: 'id-func-bar-MessageRecord', disabled: false },
    { name: '翻译', id: 'deepl-bar-icon', disabled: false },
    { name: '窗口抖动', id: 'id-func-bar-shake', disabled: false }
  ],
  chatAreaFuncList: [
    { name: '语音通话', id: 'id-func-bar-telephone', disabled: true },
    { name: '视频通话', id: 'id-func-bar-video_on', disabled: true },
    { name: '屏幕共享', id: 'id-func-bar-share_screen', disabled: true },
    {
      name: '群应用',
      id: 'id-func-bar-group_application',
      disabled: false
    },
    { name: '邀请加群', id: 'id-func-bar-group_building', disabled: false },
    { name: '工具栏项目', id: 'id-func-bar-more', disabled: false },
    { name: '发起群聊', id: 'id-func-bar-group_building', disabled: true },
    { name: '远程协助', id: 'id-func-bar-remote_control', disabled: true },
    { name: '屏蔽会话', id: 'id-func-bar-shield', disabled: false },
    { name: '添加好友', id: 'id-func-bar-add_friend', disabled: false },
    { name: '接收会话', id: 'id-func-bar-shield', disabled: false },
    { name: null, id: 'id-func-bar-more', disabled: true }
  ],
  preventEscape: false,
  advanceHookVue: true,
  setWindowIcon: true,
  autoRelanch: false,
  background: {
    overlaySiderBar: true,
    removeMask: false,
    redrawCard: true,
    backgroundVisible: true,
    blurFilter: true,
    opacity: 1,
    enabled: false,
    url: 'C:\\Users\\QingYu\\OneDrive\\图片\\Windows\\XtremeWave.png'
  },
  global: {
    UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    rkey: '&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64',
    PIC_BASE_URL: 'https://gchat.qpic.cn'
  },
  disableQtag: { level: false, title: false, all: false }
}
[!Renderer:Log:2] [DeepL] 已检测到 .chat-input-area .ck-editor
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
1f350121530bd84e6b2d575cf47d29b15b8e0f3925ad20ec0b346032bd27c96b
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7
error code v2:-8
1f350121530bd84e6b2d575cf47d29b15b8e0f3925ad20ec0b346032bd27c96b
error code v2:-8
[LLAPI] Page finished loading
返回配置文件 {
  debug: {
    console: false,
    mainConsole: false,
    autoCompileScss: false,
    showWeb: false,
    showChannedCommunication: false
  },
  compatibleLLAPI: false,
  keywordReminder: { enabled: false, keyList: [] },
  wordSearch: {
    enabled: true,
    searchUrl: 'https://www.bing.com/search?q=%search%'
  },
  imageSearch: {
    enabled: false,
    searchUrl: 'https://saucenao.com/search.php?url=%search%'
  },
  localEmoticons: {
    enabled: true,
    quickEmoticons: false,
    quickEmoticonsAutoInputOnlyOne: false,
    quickEmoticonsActiveKey: '/',
    sendBigImage: false,
    majorization: true,
    commonlyEmoticons: false,
    copyFileTolocalEmoticons: true,
    toLeftSlot: true,
    hoverShowCommonlyEmoticons: false,
    commonlyNum: 28,
    rowsSize: 6,
    localPath: 'C:\\Program Files\\LiteLoaderQQNT\\LocalExpression'
  },
  sidebar: {
    top: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    bottom: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  imageViewer: { quickClose: false, touchMove: false },
  message: {
    previreUrl: { enabled: true, dontLoadPic: false },
    goBackMainList: true,
    HighlightReplies: true,
    disabledSticker: true,
    disabledHotGIF: true,
    disabledBadge: false,
    disabledSlideMultipleSelection: false,
    convertMiniPrgmArk: true,
    showMsgTime: true,
    showMsgTimeFullDate: true,
    showMsgTimeToSenderName: true,
    replaceBtn: true,
    doubleClickReplace: true,
    removeReplyAt: true,
    mergeMessage: true,
    mergeMessageKeepTime: true,
    selfMsgToLeft: false,
    onlyAvatar: false,
    removeBubbleLimit: true,
    removeVipName: false,
    imageAutoWidth: true,
    currentLocation: false,
    overrideFont: { family: '', style: '', fullName: '', postscriptName: '' },
    preventNSFW: { enabled: false, includesAnimationEmoticons: false, list: [] },
    avatarSticky: { enabled: true, toBottom: false }
  },
  messageToImage: { enabled: false, highResolution: false, path: '' },
  preventMessageRecall: {
    enabled: true,
    localStorage: true,
    customColor: true,
    preventSelfMsg: true,
    blockAllRetractions: true,
    textColor: { light: '#ff6666', dark: '#c70000' }
  },
  tail: { enabled: false, tips: false, list: [ [Object] ] },
  textAreaFuncList: [
    { name: '表情', id: 'id-func-bar-expression', disabled: false },
    { name: '截图', id: 'id-func-bar-screenshot', disabled: true },
    { name: '文件', id: 'id-func-bar-folder', disabled: false },
    { name: '图片', id: 'id-func-bar-image', disabled: false },
    { name: '红包', id: 'id-func-bar-lucky_money', disabled: true },
    { name: '语音消息', id: 'id-func-bar-microphone_on', disabled: true },
    { name: '机器人指令', id: 'id-func-bar-channel_robot', disabled: true },
    { name: '聊天记录', id: 'id-func-bar-MessageRecord', disabled: false },
    { name: '翻译', id: 'deepl-bar-icon', disabled: false },
    { name: '窗口抖动', id: 'id-func-bar-shake', disabled: false }
  ],
  chatAreaFuncList: [
    { name: '语音通话', id: 'id-func-bar-telephone', disabled: true },
    { name: '视频通话', id: 'id-func-bar-video_on', disabled: true },
    { name: '屏幕共享', id: 'id-func-bar-share_screen', disabled: true },
    {
      name: '群应用',
      id: 'id-func-bar-group_application',
      disabled: false
    },
    { name: '邀请加群', id: 'id-func-bar-group_building', disabled: false },
    { name: '工具栏项目', id: 'id-func-bar-more', disabled: false },
    { name: '发起群聊', id: 'id-func-bar-group_building', disabled: true },
    { name: '远程协助', id: 'id-func-bar-remote_control', disabled: true },
    { name: '屏蔽会话', id: 'id-func-bar-shield', disabled: false },
    { name: '添加好友', id: 'id-func-bar-add_friend', disabled: false },
    { name: '接收会话', id: 'id-func-bar-shield', disabled: false },
    { name: null, id: 'id-func-bar-more', disabled: true }
  ],
  preventEscape: false,
  advanceHookVue: true,
  setWindowIcon: true,
  autoRelanch: false,
  background: {
    overlaySiderBar: true,
    removeMask: false,
    redrawCard: true,
    backgroundVisible: true,
    blurFilter: true,
    opacity: 1,
    enabled: false,
    url: 'C:\\Users\\QingYu\\OneDrive\\图片\\Windows\\XtremeWave.png'
  },
  global: {
    UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    rkey: '&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64',
    PIC_BASE_URL: 'https://gchat.qpic.cn'
  },
  disableQtag: { level: false, title: false, all: false }
}
21:12:57.831 > [hot update] hotUpdateApi checkHasMultipleQQ false
21:12:57.834 > [hot update] hotUpdateApi start clearOldVersions
21:12:57.835 > [hot update] hotUpdateApi curVersionZipPath is: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424.zip false
21:12:57.934 > [hot update] hotUpdateApi checkHasMultipleQQ false
21:12:57.936 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.9-22961
21:12:57.937 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
[2024/5/18 21:12:59][QQCleaner] Starting clean task...
[2024/5/18 21:12:59][QQCleaner] Scanning cache...
[2024/5/18 21:13:03][QQCleaner] Getting cache files...
[2024/5/18 21:13:03][QQCleaner] No cache files found.
[2024/5/18 21:13:03][QQCleaner] Clean complete. Total: 0

**Comment by 2584191127** [comment]
我是每天第一次启动必失效，关掉qq再打开才正常

**Comment by QingFeng-awa** [comment]
讨论请转移至 #6
